CONFIG = {
    "MONGO_HOST": 'localhost',
    "MONGO_PORT": 27017,
    "DB_NAME": "YOUR-BOT-NAME",
    "DB_DISABLE_COLLECTION": 'YOUR-DISABLE-COLLECTION',
    "DB_TOP_COLLECTION": 'YOUR-TOP-COLLECTION',
    "TELEGRAM_API_KEY": 'YOUR-TELEGRAM-API-KEY'
}